### PR TITLE
Spring Cleanup - Repo Structure

### PR DESCRIPTION
**Pull request by Nirmal4G**
Splitting from #72

### CODE REVIEW

**Comment by Nirmal4G** [comment]
This is done. No Code Change.

**Comment by onovotny** [comment]
What is the purpose of overriding the build path and intermediate paths?

**Comment by Nirmal4G** [comment]
Only for the package build, it places the package in `<repoDir>\~Packages\<config>\*.nupkg` and the build in `<repoDir>\~Build\*`

**Comment by onovotny** [comment]
I'll merge this after one change -- please revert the builds\packages stuff. Not sure it's needed at all and it adds more complexity.

The `PackageOutputPath` property can be set to specify the package output location. That part is okay, but I don't see the benefit of the other build related changes.

Thanks!

**Comment by Nirmal4G** [comment]
It is needed, since it depended by `TestProjects` and `Tests`. Can you keep them until I add those parts?

I'll make a note to do this later.

**Comment by onovotny** [comment]
Ok

**Comment by Nirmal4G** [comment]
I fixed the main build in another branch.

Here's the fix:

> .vsts-ci.yml

```yml
queue: Hosted VS2017

trigger:
  - master
  - rel/*

variables:
  BuildConfiguration: Release

steps:
- template: .vsts-shared.yml
  parameters:
    signSteps:
    - task: PowerShell@2
      displayName: Authenticode Sign artifacts
      inputs:
        filePath: Tools\Sign-Package.ps1
      env:
        SignClientUser: $(SignClientUser)
        SignClientSecret: $(SignClientSecret)
        ArtifactDirectory: $(Build.ArtifactStagingDirectory)\Packages
```

**Comment by Nirmal4G** [comment]
Some how It got rearranged on resolving merge conflicts, sorry about that

**Pull request merged**
