### PR TITLE
Use $(_TargetAssemblyProjectName) in Wpf.targets

### PR DESCRIPTION
**Pull request by wjk**
This PR contains the latest WPF update from NuGet/Home#5894. I also made a few changes to the WPF sample project, so I could test the update.

Note that I put the `*.props` and `*.targets` imports right next to each other, because I could think of no good place to separate them to. I don't know if this will break anything. If you can think of a better place for the `*.props` import to go, I'm glad to move it. Thanks!

### CODE REVIEW

**Comment by wjk** [comment]
By the way, congrats on your Ninja Cat award @onovotny!

**Comment by onovotny** [comment]
Instead of adding packages to the top-level nuget config, the sample project should be in the `\Tests` directory and in that solution. The issue is that the main project has to be built before the package is in the local temp directory.

Also, we need to respect the ordering of the props/targets. The workaround can go into the main props/targets with an extra condition to see `_TargetAssemblyProjectName` isn't blank. Not sure where that's defined yet, but we also want to ensure we're not double-importing, so needs some other condition that we're in the temporary assembly.

**Comment by wjk** [comment]
I moved the WPF NuGet `*.props` import into `MSBuild.Sdk.Extras.props`. I kept the condition intact, as I couldn't quite understand what you were asking me to add. Note that the variable in question is passed directly to the MSBuild engine by the `GenerateTemporaryTargetAssembly` task (see the picture I posted at https://github.com/NuGet/Home/issues/5894#issuecomment-388520580); it is not defined in any props or targets file.

**Comment by onovotny** [comment]
@wjk that should be fine then, I just didn't want there to be a double import if other projects set the variable.

**Comment by AArnott** [comment]
This isn't working for me, because the WPF targets doesn't define the `$(_TargetAssemblyProjectName)` property. What toolset are you using that defines that?

**Comment by AArnott** [comment]
Hmmm.... I see that property is set by a global property. I'm seeing that, but the import of my PackageReference's build folder is not happening in my WPF project anyway, while using the msbuild.sdk.extras. I'm still trying to figure out why.

**Comment by onovotny** [comment]
@AArnott The updated .NET 4.7.2 build task for WPF sets that itself

**Comment by onovotny** [comment]
How are you importing it? NuGet Package Explorer seems to be working correctly so far... https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NuGetPackageExplorer.csproj

**Comment by AArnott** [comment]
That looks like [how I'm importing it as well](https://github.com/AArnott/GuidGen/blob/NetSDK/src/GuidGen/GuidGen.csproj). 

[These are the PackageReferences](https://github.com/AArnott/GuidGen/blob/916d1458d15853fd6611cc1aabd838f68bdd2f80/src/Directory.Build.props#L12-L13) that have build authoring that the WPF project isn't picking up on my machine [or on appveyor](https://ci.appveyor.com/project/AArnott/guidgen/build/2.0.23+g9c8c9a196f.R#L22).

**Comment by onovotny** [comment]
I'm seeing this: 

```
Project "$(BaseIntermediateOutputPath)$(_TargetAssemblyProjectName).*.targets" was not imported by "C:\Users\oren\.nuget\packages\msbuild.sdk.extras\1.5.4\build\platforms\languageTargets\Wpf.targets" at (71,3), due to false condition; ('$(_TargetAssemblyProjectName)' != '' and '$(ImportProjectExtensionProps)' == 'true' and exists('$(BaseIntermediateOutputPath)')) was evaluated as ('GuidGen' != '' and 'true' == 'true' and exists('C:\dev\GuidGen\src\..\obj\GuidGen_anej0tpm_wpftmp\')).
```

**Comment by onovotny** [comment]
Your `$(BaseIntermediateOutputPath)` override isn't working for the generated project and it's getting its own version of that without the targets in it.

**Comment by onovotny** [comment]
Not sure where the issue lies, but happy to take a fix for it.

**Comment by AArnott** [comment]
Woot! Thank you. I've applied [the small fix/workaround](https://github.com/AArnott/GuidGen/commit/0faff7430a98ccbde2a43b24384690c578ad60ad) to my own repo. Not a bug or anything that msbuild.sdk.extras can do as far as I can tell. It's just my "read only source tree" property definitions that needed to account for the MSBuildProjectName changing.

**Pull request merged**
