### PR TITLE
Add support for Continua CI

### PR DESCRIPTION
**Pull request by GeertvanHorrik**

### CODE REVIEW

**Comment by onovotny** [comment]
thanks!

**Comment by kzu** [comment]
This change breaks VS. I can't load the project anymore. Get the error:

---------------------------
Microsoft Visual Studio
---------------------------
The expression """.Version" cannot be evaluated. Method 'System.String.Version' not found.  C:\Code\oss\MSBuildSdkExtras\MSBuild.Sdk.Extras\MSBuild.Sdk.Extras.targets
---------------------------
OK   
---------------------------

The failing line is precisely the one changed here, which makes sense, since it's trying to access a subproperty on a string: `'$(ContinuaCI.Version)'`.

Was it supposed to be `$(ContinuaCI_Version)` perhaps?

**Comment by kzu** [comment]
Also, what's the point of this change? It's not like the project is built anywhere *but* appveyor... Sending a cleanup PR ...

**Comment by kzu** [comment]
You can't use the syntax in the docs because they use dots in envvars and you can't consume that from MSBuild. VSTS turns dots into underscores and uses all upppercase to differentiate them. 

Also, none of that is necessary since this project doesn't built on *any* other CI than AppVeyor at the moment. Hence, I submitted #42 to clean all that up to avoid confusion.

**Pull request merged**
