### PR TITLE
Spring Cleanup - Package Structure

### PR DESCRIPTION
**Pull request by Nirmal4G**
Split from #72. Continued from #78.

### CODE REVIEW

**Comment by onovotny** [comment]
This is getting rid of the `BuildMultiTargeting` folder. We need that so it installs into the outer loop...?

**Comment by Nirmal4G** [comment]
Does it not install with just `Build` folder?

Seen many packages work fine with just `Build` folder! Is there anyway to test it?

**Comment by Nirmal4G** [comment]
Will add redirections back to the `Build` folder, if it doesn't work with the outer loop.

**Comment by Nirmal4G** [comment]
This is done. You can merge anytime.

**Comment by onovotny** [comment]
There are a lot of changes here -- can  you please highlight what they are (and why)?

**Comment by Nirmal4G** [comment]
None of these are code changes, only cosmetics and restructure, so that my original PR can be added on top of this.

**Pull request merged**
